apiVersion: v1
kind: Service
metadata:
  name: nodejs-ts-mysql-using-mysql
  labels:
    app: nodejs-ts-mysql-using-mysql
spec:
  ports:
    - port: 8080
  selector:
    app: nodejs-ts-mysql-using-mysql
