apiVersion: v1
kind: Service
metadata:
  name: nodejs-ts-mysql-using-mysql2
  labels:
    app: nodejs-ts-mysql-using-mysql2
spec:
  ports:
    - port: 8080
  selector:
    app: nodejs-ts-mysql-using-mysql2
